jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      curl -LO https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-windows-x86_64.exe
      mv bazel-*.exe bazel.exe
      mkdir /c/bazel
      mv bazel.exe /c/bazel
    displayName: 'Install Bazel'
  - bash: |
      # Simple haskell binary

      /c/bazel/bazel.exe build --crosstool_top=toolchain "///tests/data:ourclibrary" # first '/' gets eaten up
      /c/bazel/bazel.exe build --crosstool_top=toolchain "///tests/binary-simple:ccbin" # first '/' gets eaten up
      /c/bazel/bazel.exe build --crosstool_top=toolchain "///tests/binary-simple" # first '/' gets eaten up
      /c/bazel/bazel.exe build --compiler=msys-gcc "///tests/binary-custom-main" 
      /c/bazel/bazel.exe build --compiler=msys-gcc "///tests/binary-with-lib"
    # displayName: 'Run Bazel'
