jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - bash: |
      set -x
      echo $SHELL
      which true
      which ls
      which make
      which find
      set +x
    displayName: 'DEBUG'

  - bash: |
      set -e
      curl -LO https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel-1.1.0-windows-x86_64.exe
      mv bazel-*.exe bazel.exe
      mkdir /c/bazel
      mv bazel.exe /c/bazel
      /c/bazel/bazel.exe info release

    displayName: 'Install Bazel'

  - powershell: |
        Write-Host "Enable long path behavior"
        # See https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
    displayName: "Enable da long paths"

  - bash: |
        # rules_haskell can automatically install stack if it is not in $PATH,
        # yet. However, if the index has not been updated before building. Then
        # multiple parallel invocations of `stack` will both attempt to update
        # the index during build. This will fail with the following error.
        #
        #   user error (hTryLock: lock already exists: C:\Users\VssAdministrator\AppData\Roaming\stack\pantry\hackage\hackage-security-lock)
        #
        # To avoid this issue we install stack and update the index beforehand.
        # See https://github.com/tweag/stackage-head/issues/29.
        curl -sSL https://get.haskellstack.org/ | sh
        stack update
    displayName: "Install Stack"

  - bash: |
      set -e
      export MSYS2_ARG_CONV_EXCL="*"
      # Tests that build but don't run
      /c/bazel/bazel.exe build --config windows "//tests/c-compiles-still/..."
      /c/bazel/bazel.exe build --config windows "//tests/binary-with-data/..."
      /c/bazel/bazel.exe build --config windows "//tests/binary-indirect-cbits"

      # Tests that only require building
      # (when using 'test' CI fails with:
      #     ERROR: No test targets were found, yet testing was requested
      # )
      # See https://github.com/bazelbuild/bazel/issues/7291
      /c/bazel/bazel.exe build --config windows "//tests/data/..."
      /c/bazel/bazel.exe build --config windows "//tests/failures/..."
      /c/bazel/bazel.exe build --config windows "//tests/hidden-modules/..."
      /c/bazel/bazel.exe build --config windows "//tests/package-id-clash/..."

      # Tests that succeed
      /c/bazel/bazel.exe test --config windows "//tests:test-binary-simple"
      /c/bazel/bazel.exe test --config windows "//tests:test-binary-custom-main"
      /c/bazel/bazel.exe test --config windows "//tests/binary-custom-main/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-exe-path/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-data/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-lib/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-main/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-simple/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-compiler-flags/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-import/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-link-flags/..."
      /c/bazel/bazel.exe test --config windows "//tests/cpp_macro_conflict/..."
      /c/bazel/bazel.exe test --config windows "//tests/extra-source-files/..."
      /c/bazel/bazel.exe test --config windows "//tests/java_classpath/..."
      /c/bazel/bazel.exe test --config windows "//tests/generated-modules/..."
      /c/bazel/bazel.exe test --config windows "//tests/haskell_test/..."
      /c/bazel/bazel.exe test --config windows "//tests/hs-boot/..."
      /c/bazel/bazel.exe test --config windows "//tests/indirect-link/..."
      /c/bazel/bazel.exe test --config windows "//tests/library-deps/..."
      /c/bazel/bazel.exe test --config windows "//tests/library-exports/..."
      /c/bazel/bazel.exe test --config windows "//tests/library-linkstatic-flag/..."
      /c/bazel/bazel.exe test --config windows "//tests/lhs/..."
      /c/bazel/bazel.exe test --config windows "//tests/package-id-clash-binary/..."
      /c/bazel/bazel.exe test --config windows "//tests/package-name/..."
      /c/bazel/bazel.exe test --config windows "//tests/textual-hdrs/..."
      /c/bazel/bazel.exe test --config windows "//tests/two-libs/..."
      /c/bazel/bazel.exe test --config windows "//tests/encoding/..."
      /c/bazel/bazel.exe test --config windows "//tests/c-compiles/..."
      /c/bazel/bazel.exe test --config windows "//tests/stack-snapshot-deps/..."

    displayName: 'Run Bazel'
