jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      set -e
      curl -LO https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel-0.21.0-windows-x86_64.exe
      mv bazel-*.exe bazel.exe
      mkdir /c/bazel
      mv bazel.exe /c/bazel
      /c/bazel/bazel.exe info release

    displayName: 'Install Bazel'
  - bash: |
      set -e
      export MSYS2_ARG_CONV_EXCL="*"

      # Tests that build but don't run
      /c/bazel/bazel.exe build --config windows "//tests/c-compiles-still/..."
      /c/bazel/bazel.exe build --config windows "//tests/binary-with-data/..."
      /c/bazel/bazel.exe build --config windows "//tests/binary-indirect-cbits"

      # Tests that only require building
      # (when using 'test' CI fails with:
      #     ERROR: No test targets were found, yet testing was requested
      # )
      # See https://github.com/bazelbuild/bazel/issues/7291
      /c/bazel/bazel.exe build --config windows "//tests/data/..."

      # Tests that succeed
      /c/bazel/bazel.exe test --config windows "//tests:test-binary-simple"
      /c/bazel/bazel.exe test --config windows "//tests:test-binary-custom-main"
      /c/bazel/bazel.exe test --config windows "//tests/binary-custom-main/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-data/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-lib/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-main/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-simple/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-compiler-flags/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-link-flags/..."
      /c/bazel/bazel.exe test --config windows "//tests/library-deps/..."
      /c/bazel/bazel.exe test --config windows "//tests/encoding/..."
      /c/bazel/bazel.exe test --config windows "//tests/c-compiles/..."

    displayName: 'Run Bazel'
