jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - bash: |
      set -e
      curl -LO https://github.com/bazelbuild/bazel/releases/download/0.23.2/bazel-0.23.2-windows-x86_64.exe
      mv bazel-*.exe bazel.exe
      mkdir /c/bazel
      mv bazel.exe /c/bazel
      /c/bazel/bazel.exe info release

    displayName: 'Install Bazel'

  - powershell: |
        Write-Host "Enable long path behavior"
        # See https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
    displayName: "Enable da long paths"

  - bash: |
      set -e
      export MSYS2_ARG_CONV_EXCL="*"
      # Tests that build but don't run
      /c/bazel/bazel.exe build --config windows "//tests/c-compiles-still/..."
      /c/bazel/bazel.exe build --config windows "//tests/binary-with-data/..."
      /c/bazel/bazel.exe build --config windows "//tests/binary-indirect-cbits"

      # Tests that only require building
      # (when using 'test' CI fails with:
      #     ERROR: No test targets were found, yet testing was requested
      # )
      # See https://github.com/bazelbuild/bazel/issues/7291
      /c/bazel/bazel.exe build --config windows "//tests/data/..."
      /c/bazel/bazel.exe build --config windows "//tests/failures/..."
      /c/bazel/bazel.exe build --config windows "//tests/hidden-modules/..."
      /c/bazel/bazel.exe build --config windows "//tests/package-id-clash/..."

      # Tests that succeed
      /c/bazel/bazel.exe test --config windows "//tests:test-binary-simple"
      /c/bazel/bazel.exe test --config windows "//tests:test-binary-custom-main"
      /c/bazel/bazel.exe test --config windows "//tests/binary-custom-main/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-exe-path/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-data/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-lib/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-main/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-simple/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-compiler-flags/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-import/..."
      /c/bazel/bazel.exe test --config windows "//tests/binary-with-link-flags/..."
      /c/bazel/bazel.exe test --config windows "//tests/cpp_macro_conflict/..."
      /c/bazel/bazel.exe test --config windows "//tests/extra-source-files/..."
      /c/bazel/bazel.exe test --config windows "//tests/java_classpath/..."
      /c/bazel/bazel.exe test --config windows "//tests/generated-modules/..."
      /c/bazel/bazel.exe test --config windows "//tests/haskell_lint/..."
      /c/bazel/bazel.exe test --config windows "//tests/haskell_test/..."
      /c/bazel/bazel.exe test --config windows "//tests/hs-boot/..."
      /c/bazel/bazel.exe test --config windows "//tests/indirect-link/..."
      /c/bazel/bazel.exe test --config windows "//tests/library-deps/..."
      /c/bazel/bazel.exe test --config windows "//tests/library-exports/..."
      /c/bazel/bazel.exe test --config windows "//tests/library-linkstatic-flag/..."
      /c/bazel/bazel.exe test --config windows "//tests/lhs/..."
      /c/bazel/bazel.exe test --config windows "//tests/package-id-clash-binary/..."
      /c/bazel/bazel.exe test --config windows "//tests/package-name/..."
      /c/bazel/bazel.exe test --config windows "//tests/textual-hdrs/..."
      /c/bazel/bazel.exe test --config windows "//tests/two-libs/..."
      /c/bazel/bazel.exe test --config windows "//tests/encoding/..."
      /c/bazel/bazel.exe test --config windows "//tests/c-compiles/..."

    displayName: 'Run Bazel'
